using System.Text;
using DotnetAiKit.Application.Ports;
using DotnetAiKit.Core.Artifacts;
using DotnetAiKit.Core.Values;

namespace DotnetAiKit.Hosts.Codex;

/// <summary>
/// Projects to Codex CLI's shape: markdown skills, TOML agents, aggregated <c>AGENTS.md</c> conventions
/// (no per-file glob scope — capability matrix), and <c>.codex-plugin/plugin.json</c> (no agents field).
/// </summary>
public sealed class CodexProjector : IHostProjector
{
    public HostName Host => HostName.Codex;

    public IEnumerable<ProjectedFile> Project(ArtifactCorpus corpus)
    {
        foreach (var skill in corpus.Skills)
            yield return new ProjectedFile(
                $"codex/skills/{skill.Name.Value}/SKILL.md",
                new FrontmatterWriter()
                    .Scalar("name", skill.Name.Value)
                    .Quoted("description", skill.Description.Value)
                    .Compose(skill.Body));

        foreach (var agent in corpus.Agents)
            yield return ProjectAgent(agent);

        if (corpus.Rules.Count > 0)
            yield return ProjectAgentsMd(corpus.Rules);

        if (corpus.Manifest is { } manifest)
            yield return new ProjectedFile(
                ".codex-plugin/plugin.json",
                PluginJson.Write(manifest.Name, manifest.Version.ToString(), manifest.Description, manifest.Keywords));
    }

    private static ProjectedFile ProjectAgent(Agent agent)
    {
        var sb = new StringBuilder();
        sb.Append("name = ").Append(Toml(agent.Name.Value)).Append('\n');
        sb.Append("description = ").Append(Toml(agent.Description.Value)).Append('\n');
        if (agent.ReferencedSkills.Count > 0)
            sb.Append("skills = [")
              .Append(string.Join(", ", agent.ReferencedSkills.Select(s => Toml(s.Value))))
              .Append("]\n");
        return new ProjectedFile($"codex/agents/{agent.Name.Value}.toml", sb.ToString());
    }

    private static ProjectedFile ProjectAgentsMd(IReadOnlyList<Rule> rules)
    {
        var sb = new StringBuilder();
        sb.Append("# Conventions\n\n");
        sb.Append("<!-- Generated by dotnet-ai-kit. Codex applies these globally (no per-file scope). -->\n\n");
        foreach (var rule in rules)
            sb.Append("## ").Append(rule.Name.Value).Append("\n\n").Append(rule.Body.TrimEnd('\n')).Append("\n\n");
        return new ProjectedFile("codex/AGENTS.md", sb.ToString());
    }

    private static string Toml(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
