#!/usr/bin/env python
"""Generate `.claude-plugin/plugin.json` with discovered skill/command/agent paths.

Run from the repo root. Re-runnable: overwrites `.claude-plugin/plugin.json`.

The manifest declares forward-looking `agents` entries pointing to
`agents-claude/<name>.md` paths. These files are GENERATED by commit 4's T041
via `agent_generators.generate_claude_agent()`. The manifest declares them
ahead of time per the feature 019 contract (schemas/claude-plugin.schema.json).
"""

from __future__ import annotations

import json
from pathlib import Path


def main() -> None:
    repo = Path(__file__).resolve().parent.parent

    # Discover skill SKILL.md files (124 expected at feature 019 commit 3).
    skill_paths = sorted(
        str(p.relative_to(repo)).replace("\\", "/") for p in (repo / "skills").rglob("SKILL.md")
    )

    # Discover command files (27 expected).
    command_paths = sorted(
        str(p.relative_to(repo)).replace("\\", "/") for p in (repo / "commands").glob("*.md")
    )

    # Agent source files (13 expected — commit-6 T054 will rename to agents-source/).
    agent_source_paths = sorted(p.stem for p in (repo / "agents").glob("*.md") if p.stem)

    # Forward-declare agents-claude/<name>.md paths (commit 4 T041 generates files).
    agents_claude = [f"agents-claude/{stem}.md" for stem in agent_source_paths]

    manifest = {
        "name": "dotnet-ai-kit",
        "version": "1.0.0",
        "description": (
            "Full .NET development lifecycle plugin: 27 commands, 124 skills, "
            "13 specialist agents, 16 rules (5 conventions + 11 domain), "
            "12 architecture profiles, SDD workflow, code generation, AI "
            "detection for VSA / Clean Arch / DDD / CQRS Microservices."
        ),
        "agents": agents_claude,
        "skills": skill_paths,
        "commands": command_paths,
        "hooks": {"configFile": "hooks/hooks.json"},
        "mcpServers": {"configFile": ".mcp.json"},
        "lspServers": {
            "csharp-lsp": {
                "_note": (
                    "References csharp-lsp plugin dependency (declared in "
                    "`dependencies`). Requires csharp-ls binary on PATH; "
                    "verified by `dotnet-ai check` per CHK009."
                )
            }
        },
        "dependencies": ["csharp-lsp"],
    }

    target = repo / ".claude-plugin" / "plugin.json"
    target.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(
        f"wrote {target} ({len(skill_paths)} skills, {len(command_paths)} commands, "
        f"{len(agents_claude)} agents)"
    )


if __name__ == "__main__":
    main()
